# Generated by Django 4.0.6 on 2022-08-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0003_book_cover_photo_book_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('purchased', models.ManyToManyField(related_name='purchased', to='Books.book')),
                ('wishlist', models.ManyToManyField(related_name='wisher', to='Books.book')),
            ],
        ),
    ]
