# Generated by Django 4.0.6 on 2022-08-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Name',
            new_name='name',
        ),
    ]
