# Generated by Django 4.0.6 on 2022-08-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_rename_name_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
