# Generated by Django 4.0.6 on 2022-08-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_author_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ratedUsersNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
