# Generated by Django 4.0.6 on 2022-08-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_author_ratedusersno_alter_author_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rewardPoints',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ratedUsersNo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
